package generator;

import AST.jinja2.*;
import AST.python.*;
import AST.python.expr.*;

import java.util.*;

/**
 * Jinja2 Generator (Code Generator للـ Jinja2 AST).
 *
 * يمرّر البيانات من مصفوفة Python (Python AST) إلى شجرة Jinja2
 * ويُولِّد HTML جاهز للعرض.
 *
 * هذا هو جوهر متطلب المشروع: "يقوم التابع المولِّد بتمرير البيانات
 * من مصفوفة البيانات في كود الـ Python إلى الشجرة الثانية (Jinja2)"
 */
public class Jinja2Generator implements Jinja2Visitor {

    private final StringBuilder sb = new StringBuilder();
    private int indent = 0;

    // بيانات السياق المُمرَّرة من Python AST
    private final Map<String, Object> context;

    // Stack للـ for-loop variables
    private final Deque<Map<String, Object>> contextStack = new ArrayDeque<>();

    public Jinja2Generator(Map<String, Object> context) {
        this.context = new HashMap<>(context);
    }

    /**
     * يستخرج بيانات المنتجات من Python AST ويبني context map
     */
    public static Map<String, Object> extractContext(ProgramNode pythonAst) {
        Map<String, Object> ctx = new LinkedHashMap<>();

        for (PythonNode stmt : pythonAst.getStatements()) {
            if (stmt instanceof AssignmentNode asgn) {
                Object val = evaluateNode(asgn.getValue());
                if (val != null) ctx.put(asgn.getTarget(), val);
            }
        }
        return ctx;
    }

    @SuppressWarnings("unchecked")
    private static Object evaluateNode(PythonNode node) {
        if (node == null) return null;
        if (node instanceof StringLiteralNode s)  return s.getValue();
        if (node instanceof NumberLiteralNode n)  return n.getValue();
        if (node instanceof BoolLiteralNode b)    return b.getValue();
        if (node instanceof NoneLiteralNode)      return null;
        if (node instanceof IdentifierNode id)    return id.getName(); // reference
        if (node instanceof ListLiteralNode list) {
            List<Object> result = new ArrayList<>();
            for (PythonNode e : list.getElements()) result.add(evaluateNode(e));
            return result;
        }
        if (node instanceof DictLiteralNode dict) {
            Map<String, Object> map = new LinkedHashMap<>();
            for (DictLiteralNode.Entry e : dict.getEntries()) {
                String key = String.valueOf(evaluateNode(e.key()));
                map.put(key, evaluateNode(e.value()));
            }
            return map;
        }
        return node.toString();
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public String generate(Jinja2TemplateNode template) {
        sb.setLength(0);
        indent = 0;
        template.accept(this);
        return sb.toString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void emit(String s) { sb.append(s); }
    private void emitLine(String s) {
        sb.append("  ".repeat(Math.max(0, indent))).append(s).append("\n");
    }

    private Object resolve(String expr) {
        if (expr == null) return "";
        String[] parts = expr.trim().split("\\.");
        Object current = getCurrentContext().get(parts[0]);
        if (current == null) current = context.get(parts[0]);
        for (int i = 1; i < parts.length; i++) {
            if (current instanceof Map<?,?> m) current = m.get(parts[i]);
            else break;
        }
        return current != null ? current : "{{ " + expr + " }}";
    }

    private Map<String, Object> getCurrentContext() {
        return contextStack.isEmpty() ? context : contextStack.peek();
    }

    // ── Visitor ───────────────────────────────────────────────────────────────

    @Override
    public void visit(Jinja2TemplateNode node) {
        emitLine("<!-- Generated by Jinja2Generator from template: " + node.getTemplateName() + " -->");
        for (Jinja2Node ch : node.getChildren()) ch.accept(this);
    }

    @Override
    public void visit(Jinja2ExtendsNode node) {
        emit("<!-- extends: " + node.getParentTemplate() + " -->\n");
    }

    @Override
    public void visit(Jinja2BlockNode node) {
        emitLine("<!-- block: " + node.getBlockName() + " -->");
        for (Jinja2Node ch : node.getBody()) ch.accept(this);
        emitLine("<!-- endblock: " + node.getBlockName() + " -->");
    }

    @Override
    @SuppressWarnings("unchecked")
    public void visit(Jinja2ForNode node) {
        Object iterableObj = resolve(node.getIterable());
        List<Object> items = new ArrayList<>();
        if (iterableObj instanceof List<?> list) {
            items = (List<Object>) list;
        }

        for (Object item : items) {
            // Push new context with loop variable
            Map<String, Object> loopCtx = new HashMap<>(getCurrentContext());
            loopCtx.put(node.getVariable(), item);
            loopCtx.put("loop", Map.of("index", items.indexOf(item) + 1, "first", items.indexOf(item) == 0));
            contextStack.push(loopCtx);
            indent++;
            for (Jinja2Node ch : node.getBody()) ch.accept(this);
            indent--;
            contextStack.pop();
        }
    }

    @Override
    public void visit(Jinja2IfNode node) {
        // Simple condition evaluation
        boolean cond = evaluateCondition(node.getCondition());
        List<Jinja2Node> branch = cond ? node.getThenBody() : node.getElseBody();
        for (Jinja2Node ch : branch) ch.accept(this);
    }

    @Override
    public void visit(Jinja2VariableNode node) {
        Object val = resolve(node.getExpression());
        emit(val != null ? String.valueOf(val) : "");
    }

    @Override
    public void visit(Jinja2RawTextNode node) {
        if (!node.getText().isBlank()) emit(node.getText());
    }

    @Override
    public void visit(Jinja2HtmlElementNode node) {
        StringBuilder tag = new StringBuilder("<").append(node.getTagName());
        for (Jinja2AttributeNode attr : node.getAttributes()) {
            String value = attr.isJinjaExpr() ? resolveAttrExpr(attr.getValue()) : attr.getValue();
            tag.append(" ").append(attr.getName()).append("=\"").append(value).append("\"");
        }
        tag.append(">");
        emit(tag.toString());
        for (Jinja2Node ch : node.getChildren()) ch.accept(this);
        emit("</" + node.getTagName() + ">");
    }

    /**
     * يحلّ تعبير Jinja داخل خاصية HTML — يدعم متغيرات عادية وdot-access
     * بالإضافة إلى استدعاءات url_for('endpoint', param=value) عبر خريطة routes ثابتة.
     */
    private String resolveAttrExpr(String expr) {
        expr = expr.trim();

        if (expr.startsWith("url_for(")) {
            return resolveUrlFor(expr);
        }
        Object val = resolve(expr);
        return val != null ? String.valueOf(val) : "";
    }

    // خريطة الـ routes المعروفة في تطبيق Flask (تطابق flask_app/app.py)
    private static final Map<String,String> ROUTES = Map.of(
            "index",           "/",
            "add_product",     "/add",
            "edit_product",    "/edit/{product_id}",
            "product_detail",  "/product/{product_id}",
            "delete_product",  "/delete/{product_id}",
            "static",          "/static/{filename}"
    );

    private String resolveUrlFor(String expr) {
        // url_for('endpoint', product_id=product.id)  أو  url_for('static', filename='style.css')
        java.util.regex.Matcher m = java.util.regex.Pattern
                .compile("url_for\\(\\s*['\"]([^'\"]+)['\"]\\s*(?:,\\s*(\\w+)\\s*=\\s*([^)]+))?\\)")
                .matcher(expr);
        if (!m.find()) return "#";

        String endpoint = m.group(1);
        String paramName = m.group(2);
        String paramExpr = m.group(3);

        String path = ROUTES.getOrDefault(endpoint, "#");
        if (paramName != null && paramExpr != null) {
            Object val = paramExpr.trim().startsWith("'") || paramExpr.trim().startsWith("\"")
                    ? paramExpr.trim().replaceAll("^['\"]|['\"]$", "")
                    : resolve(paramExpr.trim());
            path = path.replace("{" + paramName + "}", String.valueOf(val))
                       .replace("{filename}", String.valueOf(val))
                       .replace("{product_id}", String.valueOf(val));
        }
        return path;
    }

    @Override
    public void visit(Jinja2MacroNode node) {
        // Macros are defined but not expanded here in the simple generator
        emit("<!-- macro: " + node.getName() + " defined -->");
    }

    // ── Condition Evaluator ───────────────────────────────────────────────────

    private boolean evaluateCondition(String cond) {
        if (cond == null || cond.isBlank()) return false;
        Object val = resolve(cond.trim());
        if (val instanceof Boolean b) return b;
        if (val instanceof List<?> l) return !l.isEmpty();
        if (val instanceof String s) return !s.isEmpty() && !s.startsWith("{{");
        return val != null;
    }
}
