package generator;

import AST.python.*;
import AST.python.expr.*;

import java.util.StringJoiner;

/**
 * Code Generator للـ Python AST.
 * يُولِّد كود Python/Flask نظيف من الشجرة.
 * هذا يُمثِّل مرحلة "Code Generation" في المترجم.
 */
public class PythonGenerator implements PythonVisitor {

    private final StringBuilder sb = new StringBuilder();
    private int indent = 0;

    public String generate(ProgramNode program) {
        program.accept(this);
        return sb.toString();
    }

    private void emit(String text)     { sb.append(text); }
    private void emitLine(String text) { sb.append("    ".repeat(indent)).append(text).append("\n"); }
    private void emitLine()            { sb.append("\n"); }
    private void ind()                 { sb.append("    ".repeat(indent)); }

    // ── Statements ────────────────────────────────────────────────────────────

    @Override
    public void visit(ProgramNode node) {
        emitLine("# ═══════════════════════════════════════════════════════");
        emitLine("# Flask Product Management Application");
        emitLine("# Generated by Compiler Project — Java/ANTLR4 Compiler");
        emitLine("# ═══════════════════════════════════════════════════════");
        emitLine();
        for (PythonNode stmt : node.getStatements()) {
            if (stmt != null) stmt.accept(this);
        }
    }

    @Override
    public void visit(ImportNode node) {
        if (node.isFrom()) {
            emitLine("from " + node.getModule() + " import " + String.join(", ", node.getNames()));
        } else {
            emitLine("import " + node.getModule());
        }
    }

    @Override
    public void visit(AssignmentNode node) {
        ind();
        emit(node.getTarget() + " = ");
        if (node.getValue() != null) node.getValue().accept(this);
        emit("\n");
    }

    @Override
    public void visit(FunctionDefNode node) {
        emitLine();
        // Decorators
        for (DecoratorNode d : node.getDecorators()) {
            d.accept(this);
        }
        // def signature
        StringJoiner params = new StringJoiner(", ");
        node.getParams().forEach(params::add);
        emitLine("def " + node.getName() + "(" + params + "):");
        indent++;
        if (node.getBody().isEmpty()) {
            emitLine("pass");
        } else {
            for (PythonNode s : node.getBody()) {
                if (s != null) s.accept(this);
            }
        }
        indent--;
        emitLine();
    }

    @Override
    public void visit(DecoratorNode node) {
        if (node.getArgument() == null || node.getArgument().isEmpty()) {
            emitLine("@" + node.getName());
        } else {
            emitLine("@" + node.getName() + "(" + node.getArgument() + ")");
        }
    }

    @Override
    public void visit(ReturnNode node) {
        ind();
        emit("return ");
        if (node.getValue() != null) node.getValue().accept(this);
        emit("\n");
    }

    @Override
    public void visit(ExpressionStatementNode node) {
        ind();
        if (node.getExpression() != null) node.getExpression().accept(this);
        emit("\n");
    }

    @Override
    public void visit(IfStatementNode node) {
        ind();
        emit("if ");
        if (node.getCondition() != null) node.getCondition().accept(this);
        emit(":\n");
        indent++;
        if (node.getThenBody().isEmpty()) emitLine("pass");
        else for (PythonNode s : node.getThenBody()) if (s != null) s.accept(this);
        indent--;
        if (!node.getElseBody().isEmpty()) {
            emitLine("else:");
            indent++;
            for (PythonNode s : node.getElseBody()) if (s != null) s.accept(this);
            indent--;
        }
    }

    @Override
    public void visit(ForStatementNode node) {
        ind();
        emit("for " + node.getVariable() + " in ");
        if (node.getIterable() != null) node.getIterable().accept(this);
        emit(":\n");
        indent++;
        if (node.getBody().isEmpty()) emitLine("pass");
        else for (PythonNode s : node.getBody()) if (s != null) s.accept(this);
        indent--;
    }

    @Override
    public void visit(AppendStatementNode node) {
        ind();
        emit(node.getListName() + ".append(");
        if (node.getItem() != null) node.getItem().accept(this);
        emit(")\n");
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    @Override
    public void visit(StringLiteralNode node) {
        emit("\"" + node.getValue() + "\"");
    }

    @Override
    public void visit(NumberLiteralNode node) {
        double v = node.getValue();
        if (v == (long) v) emit(String.valueOf((long) v));
        else emit(String.valueOf(v));
    }

    @Override
    public void visit(BoolLiteralNode node) {
        emit(node.getValue() ? "True" : "False");
    }

    @Override
    public void visit(NoneLiteralNode node) { emit("None"); }

    @Override
    public void visit(IdentifierNode node) { emit(node.getName()); }

    @Override
    public void visit(ListLiteralNode node) {
        emit("[\n");
        indent++;
        var elements = node.getElements();
        for (int i = 0; i < elements.size(); i++) {
            ind();
            if (elements.get(i) != null) elements.get(i).accept(this);
            if (i < elements.size() - 1) emit(",");
            emit("\n");
        }
        indent--;
        ind(); emit("]");
    }

    @Override
    public void visit(DictLiteralNode node) {
        emit("{\n");
        indent++;
        var entries = node.getEntries();
        for (int i = 0; i < entries.size(); i++) {
            ind();
            if (entries.get(i).key() != null)   entries.get(i).key().accept(this);
            emit(": ");
            if (entries.get(i).value() != null) entries.get(i).value().accept(this);
            if (i < entries.size() - 1) emit(",");
            emit("\n");
        }
        indent--;
        ind(); emit("}");
    }

    @Override
    public void visit(FunctionCallNode node) {
        if (node.getCallee() != null) node.getCallee().accept(this);
        emit("(");
        boolean first = true;
        for (PythonNode arg : node.getPositionalArgs()) {
            if (!first) emit(", ");
            if (arg != null) arg.accept(this);
            first = false;
        }
        for (var entry : node.getKeywordArgs().entrySet()) {
            if (!first) emit(", ");
            emit(entry.getKey() + "=");
            if (entry.getValue() != null) entry.getValue().accept(this);
            first = false;
        }
        emit(")");
    }

    @Override
    public void visit(AttributeAccessNode node) {
        if (node.getObject() != null) node.getObject().accept(this);
        emit("." + node.getAttribute());
    }

    @Override
    public void visit(BinaryOpNode node) {
        if (node.getLeft()  != null) node.getLeft().accept(this);
        emit(" " + node.getOperator() + " ");
        if (node.getRight() != null) node.getRight().accept(this);
    }
}
